#!/usr/bin/env python3
"""
gen_rocket.py — the rocket silhouette as pack data, sliced finely.

Same technique as tools/gen_obelisk.py: instead of stacking a few blocks, a curved body
is cut into thin rings so the taper is below a pixel in play. gen_obelisk uses 52 shaft
slices; here the profiles are:

  * an engine BELL — 10 rings on a parabolic flare from the throat to the mouth, so the
    nozzle reads as a nozzle and not as a bucket;
  * a NOSE — a tangent ogive in 16 rings, a cone in 8, a blunt cap as a dome;
  * a FAIRING — a shell plus a 12-ring ogive over the payload;
  * an INTERSTAGE — 6 rings tapering from a wide lower tank to a narrower upper one, so
    a stack of different tanks looks like one vehicle instead of stacked cans;
  * swept FINS — four stepped plates per fin so the trailing edge sweeps.

The PROFILES are computed here and written into the module as data; the module itself
is a function of the assembly, because the silhouette has to change the moment a part
does. It emits games/spacehex/shared/rocket.luau — shared, because the client draws the
same stack in the assembly preview and the warehouse icons that the server stands on
the pad. No numbers from the catalogue live in it: it takes part records.

Everything is plain Roblox primitives. Nothing is uploaded, nothing is moderated.

  python3 tools/gen_rocket.py
"""
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "games", "spacehex", "shared", "rocket.luau")

BELL_RINGS = 10
OGIVE_RINGS = 16
CONE_RINGS = 8
FAIRING_RINGS = 12
INTERSTAGE_RINGS = 6
FIN_STEPS = 4


def bell_profile(n):
    """t = 0 at the throat (top), 1 at the mouth (bottom). Radius as a fraction of the
    mouth radius. A real bell flares fast off the throat and straightens toward the lip."""
    out = []
    for i in range(n):
        t = (i + 0.5) / n
        r = 0.34 + (1.0 - 0.34) * (1 - (1 - t) ** 1.9)
        out.append((t, r))
    return out


def ogive_profile(n, fineness):
    """A tangent ogive of length L = fineness * R. t = 0 at the base, 1 at the tip.
    Radius as a fraction of the base radius."""
    R, L = 1.0, fineness
    rho = (R * R + L * L) / (2 * R)
    out = []
    for i in range(n):
        t = (i + 0.5) / n
        y = t * L
        r = math.sqrt(max(0.0, rho * rho - (L - y) ** 2)) + R - rho
        out.append((t, max(0.06, r)))
    return out


def cone_profile(n):
    return [((i + 0.5) / n, max(0.06, 1.0 - (i + 0.5) / n)) for i in range(n)]


def interstage_profile(n):
    """t = 0 at the wide end, 1 at the narrow end; a smooth ease so the join has no kink."""
    out = []
    for i in range(n):
        t = (i + 0.5) / n
        e = t * t * (3 - 2 * t)
        out.append((t, e))
    return out


def fin_steps(n):
    """Chord of each plate, bottom to top, as a fraction of the root chord: a swept fin."""
    return [1.0 - 0.62 * ((i + 0.5) / n) for i in range(n)]


def lua_pairs(pairs):
    return ", ".join("{ %.4f, %.4f }" % (t, r) for t, r in pairs)


def lua_list(values):
    return ", ".join("%.4f" % v for v in values)


TEMPLATE = r'''-- rocket — the silhouette, as data. GENERATED by tools/gen_rocket.py. Do not edit by
-- hand; edit the generator.
--
-- Shared: the server stands this on the pad and the client draws the same stack in the
-- assembly preview and in every warehouse icon. No prices and no physics live here. It
-- takes part records (thrust, prop, cd, class) and returns primitive part specs, so the
-- rocket changes the moment a part does because the data did. Everything is a plain
-- Part: nothing is uploaded, nothing is moderated.
--
-- The curves are sliced finely instead of stacked as blocks: %(bell)d rings per engine
-- bell, %(ogive)d per ogive nose, %(cone)d per cone, %(fairing)d over a fairing, %(inter)d per
-- interstage, %(fin)d stepped plates per fin. At play scale the steps are under a pixel.
--
-- Frame: y = 0 is the bottom of the lowest engine bell, +Y is up, the stack is centred
-- on the axis. Every spec carries `stage` (1 = bottom, 0 = the top section) so the loop
-- knows what to drop at separation, and `role` so it knows where the fire goes
-- (`bellMouth` is the widest ring of every bell).

local theme = require(script.Parent.theme)

local Rocket = {}

local SCALE = 1.5
local P = theme.rocket

-- Profiles: { t, r } pairs, t along the piece, r as a fraction of the reference radius.
local BELL = { %(bell_profile)s }
local OGIVE = { %(ogive_profile)s }
local CONE = { %(cone_profile)s }
local FAIRING = { %(fairing_profile)s }
local INTERSTAGE = { %(interstage_profile)s }
local FIN_CHORDS = { %(fin_chords)s }

-- ---------------------------------------------------------------- sizes

--- A tank's radius and height in studs, from how much it holds. Bigger tanks get
--- proportionally longer, which is why a real rocket is one enormous tank.
function Rocket.tankSize(part: any): (number, number)
	local prop = (part and part.prop) or 105
	local k = prop / 105
	return math.clamp(0.62 * k ^ 0.27, 0.6, 3.6) * SCALE, math.clamp(2.0 * k ^ 0.37, 2.0, 21) * SCALE
end

--- An engine bell's mouth radius and height, from thrust.
function Rocket.bellSize(part: any): (number, number)
	local thrust = (part and part.thrust) or 9000
	local k = thrust / 9000
	return math.clamp(0.42 * k ^ 0.33, 0.35, 2.4) * SCALE, math.clamp(0.7 * k ^ 0.3, 0.7, 3.4) * SCALE
end

-- ---------------------------------------------------------------- primitives

local function spec(role: string, stage: number, fields: { [string]: any }): any
	fields.role = role
	fields.stage = stage
	fields.canCollide = false
	fields.castShadow = if fields.castShadow == nil then true else fields.castShadow
	return fields
end

--- A cylinder standing on end. Roblox cylinders lie along X, so it is turned upright.
local function upright(role, stage, name, radius, height, x, y, z, color, material)
	return spec(role, stage, {
		name = name,
		shape = Enum.PartType.Cylinder,
		size = Vector3.new(height, radius * 2, radius * 2),
		cframe = CFrame.new(x, y, z) * CFrame.Angles(0, 0, math.rad(90)),
		color = color,
		material = material or Enum.Material.Metal,
	})
end

local function ball(role, stage, name, radius, x, y, z, color, material)
	return spec(role, stage, {
		name = name,
		shape = Enum.PartType.Ball,
		size = Vector3.new(radius * 2, radius * 2, radius * 2),
		cframe = CFrame.new(x, y, z),
		color = color,
		material = material or Enum.Material.Metal,
	})
end

local function block(role, stage, name, size, cframe, color, material)
	return spec(role, stage, {
		name = name,
		shape = Enum.PartType.Block,
		size = size,
		cframe = cframe,
		color = color,
		material = material or Enum.Material.Metal,
	})
end

--- Lay a profile down as rings: `profile` is { t, r } pairs, radius = r * refRadius,
--- ring i sits at y0 + t * height. Rings overlap by a hair so no seam shows.
local function rings(out, role, stage, name, profile, refRadius, height, y0, x, z, color, material)
	local sliceH = height / #profile
	for i, pair in profile do
		table.insert(
			out,
			upright(role, stage, `{name}{i}`, pair[2] * refRadius, sliceH + 0.02, x, y0 + pair[1] * height, z, color, material)
		)
	end
end

local function clusterOffsets(n: number, ring: number): { { number } }
	if n <= 1 then
		return { { 0, 0 } }
	end
	local out = {}
	for i = 1, n do
		local a = (i - 1) / n * math.pi * 2 + (if n == 4 then math.pi / 4 else 0)
		table.insert(out, { math.cos(a) * ring, math.sin(a) * ring })
	end
	return out
end

-- ---------------------------------------------------------------- pieces

--- One engine bell at (x, z) with its mouth at y0. The profile runs throat -> mouth, so
--- it is laid from the top down; the widest ring is the mouth and carries the fire.
local function bell(out, stage, index, radius, height, x, y0, z)
	local tag = `S{stage}Bell{index}`
	local flareH = height * 0.8
	local sliceH = flareH / #BELL
	for i, pair in BELL do
		local y = y0 + flareH - pair[1] * flareH
		local role = if i == #BELL then "bellMouth" else "bell"
		table.insert(out, upright(role, stage, `{tag}_{i}`, pair[2] * radius, sliceH + 0.02, x, y, z, P.bell))
	end
	table.insert(out, upright("throat", stage, `{tag}Throat`, radius * 0.34, height * 0.28, x, y0 + flareH + height * 0.1, z, P.dark))
end

local function fins(out, stage, part, radius, y0, tankH)
	if not part then
		return
	end
	local grid = (part.control or 1) > 1.5
	local count = if grid then 4 else 3
	local thick = (if grid then 0.16 else 0.1) * SCALE
	if grid then
		-- a lattice near the top of the stage, the way a booster carries them
		local span = radius * 0.85
		local height = radius * 0.85
		local y = y0 + tankH - height * 0.75
		for i = 1, count do
			local a = (i - 1) / count * math.pi * 2 + math.pi / count
			table.insert(
				out,
				block(
					"fin",
					stage,
					`S{stage}Fin{i}`,
					Vector3.new(span, height, thick),
					CFrame.new(0, y, 0) * CFrame.Angles(0, a, 0) * CFrame.new(radius + span / 2 - 0.05, 0, 0),
					P.fin,
					Enum.Material.DiamondPlate
				)
			)
		end
		return
	end
	-- swept tail fins: stepped plates whose chord shrinks going up, so the trailing edge
	-- reads as a sweep instead of a flag
	local rootChord = math.max(radius * 1.15, 0.85 * SCALE)
	local height = math.max(radius * 2.4, 1.7 * SCALE)
	local stepH = height / #FIN_CHORDS
	for i = 1, count do
		local a = (i - 1) / count * math.pi * 2 + math.pi / count
		for k, chord in FIN_CHORDS do
			local span = rootChord * chord
			local y = y0 + (k - 0.5) * stepH
			table.insert(
				out,
				block(
					"fin",
					stage,
					`S{stage}Fin{i}_{k}`,
					Vector3.new(span, stepH + 0.02, thick),
					CFrame.new(0, y, 0) * CFrame.Angles(0, a, 0) * CFrame.new(radius + span / 2 - 0.05, 0, 0),
					P.fin
				)
			)
		end
	end
end

local function recovery(out, stage, part, radius, y0, tankH)
	if not part then
		return
	end
	if (part.refund or 0) >= 0.6 then
		local len = math.max(radius * 1.5, 1.2 * SCALE)
		for i = 1, 4 do
			local a = (i - 1) / 4 * math.pi * 2
			table.insert(
				out,
				block(
					"leg",
					stage,
					`S{stage}Leg{i}`,
					Vector3.new(0.18 * SCALE, len, 0.18 * SCALE),
					CFrame.new(0, y0 + len * 0.45, 0)
						* CFrame.Angles(0, a, 0)
						* CFrame.new(radius * 0.95, 0, 0)
						* CFrame.Angles(0, 0, math.rad(-28)),
					P.dark
				)
			)
		end
	else
		table.insert(
			out,
			block(
				"chute",
				stage,
				`S{stage}Chutes`,
				Vector3.new(radius * 0.5, radius * 0.7, radius * 0.5),
				CFrame.new(radius * 0.95, y0 + tankH * 0.8, 0),
				P.dark
			)
		)
	end
end

-- ---------------------------------------------------------------- the stack

--- The whole rocket. `asm` is the assembly table, `byId` maps part id -> part record.
--- Returns the specs and the stack height. Missing parts are skipped, never errors: an
--- assembly with a hole in it still draws, and the hole is visible.
function Rocket.stack(asm: any, byId: { [string]: any }): ({ any }, number)
	local out = {}
	local y = 0
	local topR = 0.6 * SCALE
	local stages = asm.stages or {}
	local belowR: number? = nil

	for i, s in ipairs(stages) do
		local engine = s.engine and byId[s.engine]
		local tank = s.tank and byId[s.tank]
		local n = math.clamp(s.engineCount or 1, 1, 4)
		local tr, th = Rocket.tankSize(tank)
		local br, bh = Rocket.bellSize(engine)
		local ring = 0
		if n > 1 then
			ring = tr * 0.5
			br = math.min(br, tr * (if n == 2 then 0.48 else 0.42))
		else
			br = math.min(br, tr * 0.95)
		end

		-- an interstage: the lower stage's shoulder tapers to this stage's radius, and
		-- the bells sit inside it
		if belowR and math.abs(belowR - tr) > 0.15 then
			local wide, narrow = math.max(belowR, tr), math.min(belowR, tr)
			local interH = math.max((wide - narrow) * 1.1, bh * 0.9)
			local profile = {}
			for _, pair in INTERSTAGE do
				local r = if belowR > tr then wide + (narrow - wide) * pair[2] else narrow + (wide - narrow) * pair[2]
				table.insert(profile, { pair[1], r / wide })
			end
			rings(out, "interstage", i, `S{i}Interstage`, profile, wide, interH, y, 0, 0, P.body, Enum.Material.Metal)
		end

		if engine then
			for k, offset in clusterOffsets(n, ring) do
				bell(out, i, k, br, bh, offset[1], y, offset[2])
			end
		end
		local tankY = y + (if engine then bh else 0)
		if tank then
			table.insert(out, upright("tank", i, `S{i}Tank`, tr, th, 0, tankY + th / 2, 0, P.body))
			-- a shoulder band top and bottom, so a tank reads as a pressure vessel
			table.insert(out, upright("band", i, `S{i}BandLo`, tr * 1.015, 0.16 * SCALE, 0, tankY + 0.12 * SCALE, 0, P.fin))
			table.insert(out, upright("band", i, `S{i}BandHi`, tr * 1.015, 0.16 * SCALE, 0, tankY + th - 0.12 * SCALE, 0, P.fin))
			if i == 1 then
				fins(out, i, s.fins and byId[s.fins], tr, tankY, th)
			end
			recovery(out, i, s.recovery and byId[s.recovery], tr, tankY, th)
		end
		y = tankY + (if tank then th else 0)
		if s.decoupler and byId[s.decoupler] and i < #stages then
			local ringH = 0.3 * SCALE
			table.insert(out, upright("decoupler", i, `S{i}Decoupler`, tr * 1.04, ringH, 0, y + ringH / 2, 0, P.dark))
			y += ringH
		end
		topR = tr
		belowR = tr
	end

	-- the top section: guidance band, service module, payload, nose
	local gnc = asm.gnc and byId[asm.gnc]
	if gnc and (gnc.mass or 0) > 0 then
		local bandH = 0.22 * SCALE
		table.insert(out, upright("gnc", 0, "Guidance", topR * 1.01, bandH, 0, y + bandH / 2, 0, P.dark))
		y += bandH
	end
	local payload = asm.payload and byId[asm.payload]
	local nose = asm.nose and byId[asm.nose]
	local protected = nose and nose.protects
	if payload or asm.rcs or asm.dock then
		local svcR = topR * 0.88
		local svcH = 0.9 * SCALE
		table.insert(out, upright("service", 0, "Service", svcR, svcH, 0, y + svcH / 2, 0, P.body))
		if asm.rcs then
			for i = 1, 4 do
				local a = (i - 1) / 4 * math.pi * 2
				table.insert(
					out,
					block(
						"rcs",
						0,
						`Rcs{i}`,
						Vector3.new(0.3 * SCALE, 0.3 * SCALE, 0.3 * SCALE),
						CFrame.new(0, y + svcH / 2, 0) * CFrame.Angles(0, a, 0) * CFrame.new(svcR, 0, 0),
						P.dark
					)
				)
			end
		end
		y += svcH
		if asm.dock then
			local dockH = 0.2 * SCALE
			table.insert(out, upright("dock", 0, "DockingPort", topR * 0.6, dockH, 0, y + dockH / 2, 0, P.dark))
			y += dockH
		end
		if payload and not protected then
			local side = topR * 0.9
			table.insert(
				out,
				block("payload", 0, "Payload", Vector3.new(side, side, side), CFrame.new(0, y + side / 2, 0), P.payload)
			)
			y += side
		end
	end
	if nose then
		if protected then
			local fr = topR * 1.15
			local shellH = topR * 2.0
			table.insert(out, upright("nose", 0, "FairingShell", fr, shellH, 0, y + shellH / 2, 0, P.body, Enum.Material.SmoothPlastic))
			if payload then
				local side = topR * 0.9
				table.insert(
					out,
					block("payload", 0, "Payload", Vector3.new(side, side, side), CFrame.new(0, y + side / 2 + 0.1, 0), P.payload)
				)
			end
			local noseH = topR * 1.9
			rings(out, "nose", 0, "Fairing", FAIRING, fr, noseH, y + shellH, 0, 0, P.body, Enum.Material.SmoothPlastic)
			y += shellH + noseH
		elseif (nose.cd or 0.5) >= 0.4 then
			table.insert(out, ball("nose", 0, "Cap", topR, 0, y, 0, P.body))
			y += topR
		elseif (nose.cd or 0.5) >= 0.3 then
			local noseH = topR * 2.3
			rings(out, "nose", 0, "Cone", CONE, topR, noseH, y, 0, 0, P.body)
			y += noseH
		else
			local noseH = topR * 3.0
			rings(out, "nose", 0, "Ogive", OGIVE, topR, noseH, y, 0, 0, P.body)
			y += noseH
		end
	end

	return out, y
end

-- ---------------------------------------------------------------- icons

--- One part on its own, centred at the origin, for a ViewportFrame. The icon IS the part.
function Rocket.icon(part: any): { any }
	local out = {}
	local class = part.class
	if class == "engine" then
		local br, bh = Rocket.bellSize(part)
		bell(out, 1, 1, br, bh, 0, -bh / 2, 0)
	elseif class == "tank" then
		local tr, th = Rocket.tankSize(part)
		table.insert(out, upright("tank", 1, "Tank", tr, th, 0, 0, 0, P.body))
		table.insert(out, upright("band", 1, "BandLo", tr * 1.015, 0.16 * SCALE, 0, -th / 2 + 0.12 * SCALE, 0, P.fin))
		table.insert(out, upright("band", 1, "BandHi", tr * 1.015, 0.16 * SCALE, 0, th / 2 - 0.12 * SCALE, 0, P.fin))
	elseif class == "nose" then
		local r = 1.0 * SCALE
		if part.protects then
			table.insert(out, upright("nose", 0, "Shell", r * 1.15, r * 2, 0, -r, 0, P.body, Enum.Material.SmoothPlastic))
			rings(out, "nose", 0, "Fairing", FAIRING, r * 1.15, r * 1.9, 0, 0, 0, P.body, Enum.Material.SmoothPlastic)
		elseif (part.cd or 0.5) >= 0.4 then
			table.insert(out, ball("nose", 0, "Cap", r, 0, 0, 0, P.body))
		elseif (part.cd or 0.5) >= 0.3 then
			rings(out, "nose", 0, "Cone", CONE, r, r * 2.3, -r, 0, 0, P.body)
		else
			rings(out, "nose", 0, "Ogive", OGIVE, r, r * 3.0, -r * 1.4, 0, 0, P.body)
		end
	elseif class == "fin" then
		local grid = (part.control or 1) > 1.5
		if grid then
			table.insert(
				out,
				block("fin", 1, "Fin", Vector3.new(1.6 * SCALE, 1.6 * SCALE, 0.16 * SCALE), CFrame.new(0, 0, 0), P.fin, Enum.Material.DiamondPlate)
			)
		else
			local stepH = 2.6 * SCALE / #FIN_CHORDS
			for k, chord in FIN_CHORDS do
				local span = 1.6 * SCALE * chord
				table.insert(
					out,
					block("fin", 1, `Fin{k}`, Vector3.new(span, stepH + 0.02, 0.1 * SCALE), CFrame.new(span / 2 - 0.8 * SCALE, (k - 0.5) * stepH - 1.3 * SCALE, 0), P.fin)
				)
			end
		end
	elseif class == "gnc" then
		table.insert(out, block("gnc", 0, "Box", Vector3.new(1.4, 0.9, 1.4) * SCALE, CFrame.new(0, 0, 0), P.dark))
		table.insert(out, block("gnc", 0, "Stripe", Vector3.new(1.45, 0.16, 0.3) * SCALE, CFrame.new(0, 0.2, 0), P.body, Enum.Material.Neon))
	elseif class == "decoupler" then
		table.insert(out, upright("decoupler", 1, "Ring", 1.2 * SCALE, 0.35 * SCALE, 0, 0, 0, P.dark))
	elseif class == "recovery" then
		if (part.refund or 0) >= 0.6 then
			for i = 1, 4 do
				local a = (i - 1) / 4 * math.pi * 2
				table.insert(
					out,
					block(
						"leg",
						1,
						`Leg{i}`,
						Vector3.new(0.18, 2.2, 0.18) * SCALE,
						CFrame.new(0, 0, 0) * CFrame.Angles(0, a, 0) * CFrame.new(0.7 * SCALE, 0, 0) * CFrame.Angles(0, 0, math.rad(-28)),
						P.dark
					)
				)
			end
		else
			table.insert(out, block("chute", 1, "Pack", Vector3.new(1.0, 1.4, 1.0) * SCALE, CFrame.new(0, 0, 0), P.dark))
			table.insert(out, ball("chute", 1, "Canopy", 0.8 * SCALE, 0, 1.1 * SCALE, 0, P.body, Enum.Material.Fabric))
		end
	elseif class == "payload" then
		if part.needsFairing then
			table.insert(out, block("payload", 0, "Bus", Vector3.new(1.0, 1.0, 1.0) * SCALE, CFrame.new(0, 0, 0), P.payload))
			table.insert(out, block("payload", 0, "PanelA", Vector3.new(2.2, 0.08, 0.9) * SCALE, CFrame.new(1.4 * SCALE, 0, 0), P.dark))
			table.insert(out, block("payload", 0, "PanelB", Vector3.new(2.2, 0.08, 0.9) * SCALE, CFrame.new(-1.4 * SCALE, 0, 0), P.dark))
		else
			table.insert(out, block("payload", 0, "Ballast", Vector3.new(1.2, 1.2, 1.2) * SCALE, CFrame.new(0, 0, 0), P.dark))
		end
	elseif class == "rcs" then
		table.insert(out, block("rcs", 0, "Body", Vector3.new(1.0, 0.7, 1.0) * SCALE, CFrame.new(0, 0, 0), P.body))
		for i = 1, 4 do
			local a = (i - 1) / 4 * math.pi * 2
			table.insert(
				out,
				block("rcs", 0, `Nozzle{i}`, Vector3.new(0.3, 0.3, 0.3) * SCALE, CFrame.new(0, 0, 0) * CFrame.Angles(0, a, 0) * CFrame.new(0.6 * SCALE, 0, 0), P.dark)
			)
		end
	elseif class == "dock" then
		table.insert(out, upright("dock", 0, "Port", 1.1 * SCALE, 0.3 * SCALE, 0, 0, 0, P.dark))
		table.insert(out, upright("dock", 0, "Collar", 0.7 * SCALE, 0.5 * SCALE, 0, 0.3 * SCALE, 0, P.body))
	else
		-- a pad tier: a flat disc
		table.insert(out, upright("pad", 0, "Pad", 1.4 * SCALE, 0.25 * SCALE, 0, 0, 0, theme.pad, Enum.Material.DiamondPlate))
	end
	return out
end

return Rocket
'''

body = TEMPLATE % dict(
    bell=BELL_RINGS, ogive=OGIVE_RINGS, cone=CONE_RINGS, fairing=FAIRING_RINGS, inter=INTERSTAGE_RINGS, fin=FIN_STEPS,
    bell_profile=lua_pairs(bell_profile(BELL_RINGS)),
    ogive_profile=lua_pairs(ogive_profile(OGIVE_RINGS, 3.0)),
    cone_profile=lua_pairs(cone_profile(CONE_RINGS)),
    fairing_profile=lua_pairs(ogive_profile(FAIRING_RINGS, 1.65)),
    interstage_profile=lua_pairs(interstage_profile(INTERSTAGE_RINGS)),
    fin_chords=lua_list(fin_steps(FIN_STEPS)),
)
open(OUT, "w").write(body)
print("wrote", OUT, "(%d lines)" % body.count("\n"))

# The pre-commit gate runs `stylua --check games`; a generated file that is not in the
# repo's format would block every commit after a regenerate. Format it here, best effort.
import shutil
import subprocess

stylua = shutil.which("stylua") or os.path.expanduser("~/.rokit/bin/stylua")
if os.path.exists(stylua):
    subprocess.run([stylua, OUT], check=False)
    print("formatted with stylua")
else:
    print("stylua not found; run `stylua games/spacehex/shared/rocket.luau` before committing")
